#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBML.DBML
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdventureWorks2012")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRANDOMDATA(RANDOMDATA instance);
    partial void UpdateRANDOMDATA(RANDOMDATA instance);
    partial void DeleteRANDOMDATA(RANDOMDATA instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DBML.Properties.Settings.Default.AdventureWorks2012ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RANDOMDATA> RANDOMDATAs
		{
			get
			{
				return this.GetTable<RANDOMDATA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RANDOMDATA")]
	public partial class RANDOMDATA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PKID;
		
		private string _COLUMN1;
		
		private string _COLUMN2;
		
		private string _COLUMN3;
		
		private string _COLUMN4;
		
		private string _COLUMN5;
		
		private string _COLUMN6;
		
		private string _COLUMN7;
		
		private string _COLUMN8;
		
		private string _COLUMN9;
		
		private string _COLUMN10;
		
		private string _COLUMN11;
		
		private string _COLUMN12;
		
		private string _COLUMN13;
		
		private string _COLUMNN14;
		
		private string _COLUMNO15;
		
		private string _COLUMNO16;
		
		private string _COLUMNO17;
		
		private string _COLUMNO18;
		
		private string _COLUMNO19;
		
		private string _COLUMN20;
		
		private string _COLUMN21;
		
		private string _COLUMN22;
		
		private string _COLUMN23;
		
		private string _COLUMN24;
		
		private string _COLUMN25;
		
		private string _COLUMN26;
		
		private string _COLUMN27;
		
		private string _COLUMN28;
		
		private string _COLUMN29;
		
		private string _COLUMN30;
		
		private string _COLUMN31;
		
		private string _COLUMN32;
		
		private string _COLUMN33;
		
		private string _COLUMN34;
		
		private string _COLUMN35;
		
		private string _COLUMN36;
		
		private string _COLUMN37;
		
		private string _COLUMN38;
		
		private string _COLUMN39;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKIDChanging(int value);
    partial void OnPKIDChanged();
    partial void OnCOLUMN1Changing(string value);
    partial void OnCOLUMN1Changed();
    partial void OnCOLUMN2Changing(string value);
    partial void OnCOLUMN2Changed();
    partial void OnCOLUMN3Changing(string value);
    partial void OnCOLUMN3Changed();
    partial void OnCOLUMN4Changing(string value);
    partial void OnCOLUMN4Changed();
    partial void OnCOLUMN5Changing(string value);
    partial void OnCOLUMN5Changed();
    partial void OnCOLUMN6Changing(string value);
    partial void OnCOLUMN6Changed();
    partial void OnCOLUMN7Changing(string value);
    partial void OnCOLUMN7Changed();
    partial void OnCOLUMN8Changing(string value);
    partial void OnCOLUMN8Changed();
    partial void OnCOLUMN9Changing(string value);
    partial void OnCOLUMN9Changed();
    partial void OnCOLUMN10Changing(string value);
    partial void OnCOLUMN10Changed();
    partial void OnCOLUMN11Changing(string value);
    partial void OnCOLUMN11Changed();
    partial void OnCOLUMN12Changing(string value);
    partial void OnCOLUMN12Changed();
    partial void OnCOLUMN13Changing(string value);
    partial void OnCOLUMN13Changed();
    partial void OnCOLUMNN14Changing(string value);
    partial void OnCOLUMNN14Changed();
    partial void OnCOLUMNO15Changing(string value);
    partial void OnCOLUMNO15Changed();
    partial void OnCOLUMNO16Changing(string value);
    partial void OnCOLUMNO16Changed();
    partial void OnCOLUMNO17Changing(string value);
    partial void OnCOLUMNO17Changed();
    partial void OnCOLUMNO18Changing(string value);
    partial void OnCOLUMNO18Changed();
    partial void OnCOLUMNO19Changing(string value);
    partial void OnCOLUMNO19Changed();
    partial void OnCOLUMN20Changing(string value);
    partial void OnCOLUMN20Changed();
    partial void OnCOLUMN21Changing(string value);
    partial void OnCOLUMN21Changed();
    partial void OnCOLUMN22Changing(string value);
    partial void OnCOLUMN22Changed();
    partial void OnCOLUMN23Changing(string value);
    partial void OnCOLUMN23Changed();
    partial void OnCOLUMN24Changing(string value);
    partial void OnCOLUMN24Changed();
    partial void OnCOLUMN25Changing(string value);
    partial void OnCOLUMN25Changed();
    partial void OnCOLUMN26Changing(string value);
    partial void OnCOLUMN26Changed();
    partial void OnCOLUMN27Changing(string value);
    partial void OnCOLUMN27Changed();
    partial void OnCOLUMN28Changing(string value);
    partial void OnCOLUMN28Changed();
    partial void OnCOLUMN29Changing(string value);
    partial void OnCOLUMN29Changed();
    partial void OnCOLUMN30Changing(string value);
    partial void OnCOLUMN30Changed();
    partial void OnCOLUMN31Changing(string value);
    partial void OnCOLUMN31Changed();
    partial void OnCOLUMN32Changing(string value);
    partial void OnCOLUMN32Changed();
    partial void OnCOLUMN33Changing(string value);
    partial void OnCOLUMN33Changed();
    partial void OnCOLUMN34Changing(string value);
    partial void OnCOLUMN34Changed();
    partial void OnCOLUMN35Changing(string value);
    partial void OnCOLUMN35Changed();
    partial void OnCOLUMN36Changing(string value);
    partial void OnCOLUMN36Changed();
    partial void OnCOLUMN37Changing(string value);
    partial void OnCOLUMN37Changed();
    partial void OnCOLUMN38Changing(string value);
    partial void OnCOLUMN38Changed();
    partial void OnCOLUMN39Changing(string value);
    partial void OnCOLUMN39Changed();
    #endregion
		
		public RANDOMDATA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PKID
		{
			get
			{
				return this._PKID;
			}
			set
			{
				if ((this._PKID != value))
				{
					this.OnPKIDChanging(value);
					this.SendPropertyChanging();
					this._PKID = value;
					this.SendPropertyChanged("PKID");
					this.OnPKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN1", DbType="VarChar(100)")]
		public string COLUMN1
		{
			get
			{
				return this._COLUMN1;
			}
			set
			{
				if ((this._COLUMN1 != value))
				{
					this.OnCOLUMN1Changing(value);
					this.SendPropertyChanging();
					this._COLUMN1 = value;
					this.SendPropertyChanged("COLUMN1");
					this.OnCOLUMN1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN2", DbType="VarChar(100)")]
		public string COLUMN2
		{
			get
			{
				return this._COLUMN2;
			}
			set
			{
				if ((this._COLUMN2 != value))
				{
					this.OnCOLUMN2Changing(value);
					this.SendPropertyChanging();
					this._COLUMN2 = value;
					this.SendPropertyChanged("COLUMN2");
					this.OnCOLUMN2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN3", DbType="NVarChar(100)")]
		public string COLUMN3
		{
			get
			{
				return this._COLUMN3;
			}
			set
			{
				if ((this._COLUMN3 != value))
				{
					this.OnCOLUMN3Changing(value);
					this.SendPropertyChanging();
					this._COLUMN3 = value;
					this.SendPropertyChanged("COLUMN3");
					this.OnCOLUMN3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN4", DbType="NVarChar(100)")]
		public string COLUMN4
		{
			get
			{
				return this._COLUMN4;
			}
			set
			{
				if ((this._COLUMN4 != value))
				{
					this.OnCOLUMN4Changing(value);
					this.SendPropertyChanging();
					this._COLUMN4 = value;
					this.SendPropertyChanged("COLUMN4");
					this.OnCOLUMN4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN5", DbType="NVarChar(100)")]
		public string COLUMN5
		{
			get
			{
				return this._COLUMN5;
			}
			set
			{
				if ((this._COLUMN5 != value))
				{
					this.OnCOLUMN5Changing(value);
					this.SendPropertyChanging();
					this._COLUMN5 = value;
					this.SendPropertyChanged("COLUMN5");
					this.OnCOLUMN5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN6", DbType="NVarChar(100)")]
		public string COLUMN6
		{
			get
			{
				return this._COLUMN6;
			}
			set
			{
				if ((this._COLUMN6 != value))
				{
					this.OnCOLUMN6Changing(value);
					this.SendPropertyChanging();
					this._COLUMN6 = value;
					this.SendPropertyChanged("COLUMN6");
					this.OnCOLUMN6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN7", DbType="NVarChar(100)")]
		public string COLUMN7
		{
			get
			{
				return this._COLUMN7;
			}
			set
			{
				if ((this._COLUMN7 != value))
				{
					this.OnCOLUMN7Changing(value);
					this.SendPropertyChanging();
					this._COLUMN7 = value;
					this.SendPropertyChanged("COLUMN7");
					this.OnCOLUMN7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN8", DbType="NVarChar(100)")]
		public string COLUMN8
		{
			get
			{
				return this._COLUMN8;
			}
			set
			{
				if ((this._COLUMN8 != value))
				{
					this.OnCOLUMN8Changing(value);
					this.SendPropertyChanging();
					this._COLUMN8 = value;
					this.SendPropertyChanged("COLUMN8");
					this.OnCOLUMN8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN9", DbType="NVarChar(100)")]
		public string COLUMN9
		{
			get
			{
				return this._COLUMN9;
			}
			set
			{
				if ((this._COLUMN9 != value))
				{
					this.OnCOLUMN9Changing(value);
					this.SendPropertyChanging();
					this._COLUMN9 = value;
					this.SendPropertyChanged("COLUMN9");
					this.OnCOLUMN9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN10", DbType="NVarChar(100)")]
		public string COLUMN10
		{
			get
			{
				return this._COLUMN10;
			}
			set
			{
				if ((this._COLUMN10 != value))
				{
					this.OnCOLUMN10Changing(value);
					this.SendPropertyChanging();
					this._COLUMN10 = value;
					this.SendPropertyChanged("COLUMN10");
					this.OnCOLUMN10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN11", DbType="NVarChar(100)")]
		public string COLUMN11
		{
			get
			{
				return this._COLUMN11;
			}
			set
			{
				if ((this._COLUMN11 != value))
				{
					this.OnCOLUMN11Changing(value);
					this.SendPropertyChanging();
					this._COLUMN11 = value;
					this.SendPropertyChanged("COLUMN11");
					this.OnCOLUMN11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN12", DbType="NVarChar(100)")]
		public string COLUMN12
		{
			get
			{
				return this._COLUMN12;
			}
			set
			{
				if ((this._COLUMN12 != value))
				{
					this.OnCOLUMN12Changing(value);
					this.SendPropertyChanging();
					this._COLUMN12 = value;
					this.SendPropertyChanged("COLUMN12");
					this.OnCOLUMN12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN13", DbType="NVarChar(100)")]
		public string COLUMN13
		{
			get
			{
				return this._COLUMN13;
			}
			set
			{
				if ((this._COLUMN13 != value))
				{
					this.OnCOLUMN13Changing(value);
					this.SendPropertyChanging();
					this._COLUMN13 = value;
					this.SendPropertyChanged("COLUMN13");
					this.OnCOLUMN13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMNN14", DbType="NVarChar(100)")]
		public string COLUMNN14
		{
			get
			{
				return this._COLUMNN14;
			}
			set
			{
				if ((this._COLUMNN14 != value))
				{
					this.OnCOLUMNN14Changing(value);
					this.SendPropertyChanging();
					this._COLUMNN14 = value;
					this.SendPropertyChanged("COLUMNN14");
					this.OnCOLUMNN14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMNO15", DbType="NVarChar(100)")]
		public string COLUMNO15
		{
			get
			{
				return this._COLUMNO15;
			}
			set
			{
				if ((this._COLUMNO15 != value))
				{
					this.OnCOLUMNO15Changing(value);
					this.SendPropertyChanging();
					this._COLUMNO15 = value;
					this.SendPropertyChanged("COLUMNO15");
					this.OnCOLUMNO15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMNO16", DbType="NVarChar(100)")]
		public string COLUMNO16
		{
			get
			{
				return this._COLUMNO16;
			}
			set
			{
				if ((this._COLUMNO16 != value))
				{
					this.OnCOLUMNO16Changing(value);
					this.SendPropertyChanging();
					this._COLUMNO16 = value;
					this.SendPropertyChanged("COLUMNO16");
					this.OnCOLUMNO16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMNO17", DbType="NVarChar(100)")]
		public string COLUMNO17
		{
			get
			{
				return this._COLUMNO17;
			}
			set
			{
				if ((this._COLUMNO17 != value))
				{
					this.OnCOLUMNO17Changing(value);
					this.SendPropertyChanging();
					this._COLUMNO17 = value;
					this.SendPropertyChanged("COLUMNO17");
					this.OnCOLUMNO17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMNO18", DbType="NVarChar(100)")]
		public string COLUMNO18
		{
			get
			{
				return this._COLUMNO18;
			}
			set
			{
				if ((this._COLUMNO18 != value))
				{
					this.OnCOLUMNO18Changing(value);
					this.SendPropertyChanging();
					this._COLUMNO18 = value;
					this.SendPropertyChanged("COLUMNO18");
					this.OnCOLUMNO18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMNO19", DbType="NVarChar(100)")]
		public string COLUMNO19
		{
			get
			{
				return this._COLUMNO19;
			}
			set
			{
				if ((this._COLUMNO19 != value))
				{
					this.OnCOLUMNO19Changing(value);
					this.SendPropertyChanging();
					this._COLUMNO19 = value;
					this.SendPropertyChanged("COLUMNO19");
					this.OnCOLUMNO19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN20", DbType="NVarChar(100)")]
		public string COLUMN20
		{
			get
			{
				return this._COLUMN20;
			}
			set
			{
				if ((this._COLUMN20 != value))
				{
					this.OnCOLUMN20Changing(value);
					this.SendPropertyChanging();
					this._COLUMN20 = value;
					this.SendPropertyChanged("COLUMN20");
					this.OnCOLUMN20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN21", DbType="NVarChar(100)")]
		public string COLUMN21
		{
			get
			{
				return this._COLUMN21;
			}
			set
			{
				if ((this._COLUMN21 != value))
				{
					this.OnCOLUMN21Changing(value);
					this.SendPropertyChanging();
					this._COLUMN21 = value;
					this.SendPropertyChanged("COLUMN21");
					this.OnCOLUMN21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN22", DbType="NVarChar(100)")]
		public string COLUMN22
		{
			get
			{
				return this._COLUMN22;
			}
			set
			{
				if ((this._COLUMN22 != value))
				{
					this.OnCOLUMN22Changing(value);
					this.SendPropertyChanging();
					this._COLUMN22 = value;
					this.SendPropertyChanged("COLUMN22");
					this.OnCOLUMN22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN23", DbType="NVarChar(100)")]
		public string COLUMN23
		{
			get
			{
				return this._COLUMN23;
			}
			set
			{
				if ((this._COLUMN23 != value))
				{
					this.OnCOLUMN23Changing(value);
					this.SendPropertyChanging();
					this._COLUMN23 = value;
					this.SendPropertyChanged("COLUMN23");
					this.OnCOLUMN23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN24", DbType="NVarChar(100)")]
		public string COLUMN24
		{
			get
			{
				return this._COLUMN24;
			}
			set
			{
				if ((this._COLUMN24 != value))
				{
					this.OnCOLUMN24Changing(value);
					this.SendPropertyChanging();
					this._COLUMN24 = value;
					this.SendPropertyChanged("COLUMN24");
					this.OnCOLUMN24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN25", DbType="NVarChar(100)")]
		public string COLUMN25
		{
			get
			{
				return this._COLUMN25;
			}
			set
			{
				if ((this._COLUMN25 != value))
				{
					this.OnCOLUMN25Changing(value);
					this.SendPropertyChanging();
					this._COLUMN25 = value;
					this.SendPropertyChanged("COLUMN25");
					this.OnCOLUMN25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN26", DbType="NVarChar(100)")]
		public string COLUMN26
		{
			get
			{
				return this._COLUMN26;
			}
			set
			{
				if ((this._COLUMN26 != value))
				{
					this.OnCOLUMN26Changing(value);
					this.SendPropertyChanging();
					this._COLUMN26 = value;
					this.SendPropertyChanged("COLUMN26");
					this.OnCOLUMN26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN27", DbType="NVarChar(100)")]
		public string COLUMN27
		{
			get
			{
				return this._COLUMN27;
			}
			set
			{
				if ((this._COLUMN27 != value))
				{
					this.OnCOLUMN27Changing(value);
					this.SendPropertyChanging();
					this._COLUMN27 = value;
					this.SendPropertyChanged("COLUMN27");
					this.OnCOLUMN27Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN28", DbType="NVarChar(100)")]
		public string COLUMN28
		{
			get
			{
				return this._COLUMN28;
			}
			set
			{
				if ((this._COLUMN28 != value))
				{
					this.OnCOLUMN28Changing(value);
					this.SendPropertyChanging();
					this._COLUMN28 = value;
					this.SendPropertyChanged("COLUMN28");
					this.OnCOLUMN28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN29", DbType="NVarChar(100)")]
		public string COLUMN29
		{
			get
			{
				return this._COLUMN29;
			}
			set
			{
				if ((this._COLUMN29 != value))
				{
					this.OnCOLUMN29Changing(value);
					this.SendPropertyChanging();
					this._COLUMN29 = value;
					this.SendPropertyChanged("COLUMN29");
					this.OnCOLUMN29Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN30", DbType="NVarChar(100)")]
		public string COLUMN30
		{
			get
			{
				return this._COLUMN30;
			}
			set
			{
				if ((this._COLUMN30 != value))
				{
					this.OnCOLUMN30Changing(value);
					this.SendPropertyChanging();
					this._COLUMN30 = value;
					this.SendPropertyChanged("COLUMN30");
					this.OnCOLUMN30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN31", DbType="NVarChar(100)")]
		public string COLUMN31
		{
			get
			{
				return this._COLUMN31;
			}
			set
			{
				if ((this._COLUMN31 != value))
				{
					this.OnCOLUMN31Changing(value);
					this.SendPropertyChanging();
					this._COLUMN31 = value;
					this.SendPropertyChanged("COLUMN31");
					this.OnCOLUMN31Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN32", DbType="NVarChar(100)")]
		public string COLUMN32
		{
			get
			{
				return this._COLUMN32;
			}
			set
			{
				if ((this._COLUMN32 != value))
				{
					this.OnCOLUMN32Changing(value);
					this.SendPropertyChanging();
					this._COLUMN32 = value;
					this.SendPropertyChanged("COLUMN32");
					this.OnCOLUMN32Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN33", DbType="NVarChar(100)")]
		public string COLUMN33
		{
			get
			{
				return this._COLUMN33;
			}
			set
			{
				if ((this._COLUMN33 != value))
				{
					this.OnCOLUMN33Changing(value);
					this.SendPropertyChanging();
					this._COLUMN33 = value;
					this.SendPropertyChanged("COLUMN33");
					this.OnCOLUMN33Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN34", DbType="NVarChar(100)")]
		public string COLUMN34
		{
			get
			{
				return this._COLUMN34;
			}
			set
			{
				if ((this._COLUMN34 != value))
				{
					this.OnCOLUMN34Changing(value);
					this.SendPropertyChanging();
					this._COLUMN34 = value;
					this.SendPropertyChanged("COLUMN34");
					this.OnCOLUMN34Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN35", DbType="NVarChar(100)")]
		public string COLUMN35
		{
			get
			{
				return this._COLUMN35;
			}
			set
			{
				if ((this._COLUMN35 != value))
				{
					this.OnCOLUMN35Changing(value);
					this.SendPropertyChanging();
					this._COLUMN35 = value;
					this.SendPropertyChanged("COLUMN35");
					this.OnCOLUMN35Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN36", DbType="NVarChar(100)")]
		public string COLUMN36
		{
			get
			{
				return this._COLUMN36;
			}
			set
			{
				if ((this._COLUMN36 != value))
				{
					this.OnCOLUMN36Changing(value);
					this.SendPropertyChanging();
					this._COLUMN36 = value;
					this.SendPropertyChanged("COLUMN36");
					this.OnCOLUMN36Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN37", DbType="NVarChar(100)")]
		public string COLUMN37
		{
			get
			{
				return this._COLUMN37;
			}
			set
			{
				if ((this._COLUMN37 != value))
				{
					this.OnCOLUMN37Changing(value);
					this.SendPropertyChanging();
					this._COLUMN37 = value;
					this.SendPropertyChanged("COLUMN37");
					this.OnCOLUMN37Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN38", DbType="NVarChar(100)")]
		public string COLUMN38
		{
			get
			{
				return this._COLUMN38;
			}
			set
			{
				if ((this._COLUMN38 != value))
				{
					this.OnCOLUMN38Changing(value);
					this.SendPropertyChanging();
					this._COLUMN38 = value;
					this.SendPropertyChanged("COLUMN38");
					this.OnCOLUMN38Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN39", DbType="NVarChar(100)")]
		public string COLUMN39
		{
			get
			{
				return this._COLUMN39;
			}
			set
			{
				if ((this._COLUMN39 != value))
				{
					this.OnCOLUMN39Changing(value);
					this.SendPropertyChanging();
					this._COLUMN39 = value;
					this.SendPropertyChanged("COLUMN39");
					this.OnCOLUMN39Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
